apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: pg-port
      protocol: TCP
      port: 5432
      targetPort: 5432
